app:
    resource: '@AppBundle/Controller/'
    type: annotation

app_admin:
    resource: '@AppBundle/Controller/Admin/'
    type: annotation
    prefix: /admin/

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"